apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mlki
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-mlki@sha256:ccfb91799c8b6f70ca8da3612d29ea5d2158ecebf7f39aa57f2c48c8bf6be683
        name: my-nodejs
        resources: {}
status: {}
